services:
  _defaults:
    public: true

  mymodule.testservice:
    class: PrestaShop\Module\MyModule\TestService

  # mymodule.product_repository:
  #   class: PrestaShop\Module\MyModule\Repository\ProductRepository
  #   arguments:
  #     $connection: "@doctrine.dbal.default_connection"
  #     $databasePrefix: "%database_prefix%"
